### ISSUE TITLE
csv file read as `utf-8`

### ISSUE THREAD

**Issue by ohoroyoi** [itachiRedhair/react-dropzone-csv-to-json#1]
thanks you are my life saver! 

but I installed your repository, it can't be used directly.
I'll post it later.

in this issue, I recommend ` reader.readAsText(file, 'ISO-8859-1');` , rather than `reader.readAsBinaryString(file);` in your DropZone.jsx

**Comment by itachiRedhair** [comment]
Pull request?

**Comment by ohoroyoi** [comment]
ok
